version: '3.8'

services:
  desoscamreport:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desoscamreport
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_DESO_NODE_URL=https://safetynet.social
      - NEXT_PUBLIC_IDENTITY_URL=https://identity.deso.org
      - NEXT_PUBLIC_APP_NAME=DeSo Scam Report
      - NEXT_PUBLIC_APP_DOMAIN=desoscamreport.safetynet.social
      - DESO_PUBLIC_KEY=BC1YLitoF835xNLJJriQpfCQBXQzJVsqpcU7KMGnuTQiNyASu4CoSAD
      - DESO_SEED_HEX=${DESO_SEED_HEX}
    networks:
      - deso-network
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: desoscamreport-nginx
    restart: unless-stopped
    ports:
      - "8080:80"   # Use port 8080 for HTTP to avoid conflicts
      - "8443:443"  # Use port 8443 for HTTPS to avoid conflicts
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - deso-network
    depends_on:
      - desoscamreport
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: desoscamreport-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  deso-network:
    driver: bridge
    name: deso-scam-network

volumes:
  certbot_conf:
  certbot_www:
