version: '3.8'

services:
  desoscamreport:
    build: .
    container_name: desoscamreport
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_DESO_NODE_URL=https://safetynet.social
      - NEXT_PUBLIC_IDENTITY_URL=https://identity.deso.org
      - NEXT_PUBLIC_APP_NAME=DeSo Scam Report
      - NEXT_PUBLIC_APP_DOMAIN=desoscamreport.safetynet.social
      - DESO_PUBLIC_KEY=BC1YLitoF835xNLJJriQpfCQBXQzJVsqpcU7KMGnuTQiNyASu4CoSAD
    networks:
      - deso-scam-network
    healthcheck:
      test: ["CMD", "node", "/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: desoscamreport-nginx-http
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx-http.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - desoscamreport
    networks:
      - deso-scam-network

  certbot:
    image: certbot/certbot:latest
    container_name: desoscamreport-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  deso-scam-network:
    driver: bridge
    name: deso-scam-network
